"""Input sanitization and validation utilities.

Provides defense-in-depth sanitization for user-provided text before it is
injected into LLM prompts or used in any downstream processing.
"""

from __future__ import annotations

import logging
import re
import unicodedata

logger = logging.getLogger(__name__)

# Maximum allowed lengths for user inputs
MAX_QUESTION_LENGTH = 2000
MAX_FILENAME_LENGTH = 255

# Characters allowed in column names (for display/reference only, not execution)
_SAFE_COLUMN_NAME_RE = re.compile(r"^[\w\s\-\.\(\)\/\%\#\@\$\£\€]+$", re.UNICODE)

# Patterns that look like prompt injection attempts
_PROMPT_INJECTION_PATTERNS = [
    re.compile(r"ignore\s+(previous|all|above|prior)\s+instructions?", re.IGNORECASE),
    re.compile(r"you\s+are\s+now\s+(a|an|DAN)", re.IGNORECASE),
    re.compile(r"(forget|disregard)\s+(your|all)\s+(instructions?|rules?|guidelines?)", re.IGNORECASE),
    re.compile(r"(system|hidden)\s+prompt", re.IGNORECASE),
    re.compile(r"jailbreak", re.IGNORECASE),
    re.compile(r"pretend\s+(you\s+are|to\s+be)", re.IGNORECASE),
]

# Dangerous Python patterns that should never appear in generated code
_DANGEROUS_CODE_PATTERNS = [
    re.compile(r"\bimport\s+os\b"),
    re.compile(r"\bimport\s+sys\b"),
    re.compile(r"\bimport\s+subprocess\b"),
    re.compile(r"\bopen\s*\("),
    re.compile(r"\beval\s*\("),
    re.compile(r"\bexec\s*\("),
    re.compile(r"__import__\s*\("),
    re.compile(r"\bgetattr\s*\(.*__"),
    re.compile(r"socket\s*\."),
    re.compile(r"requests?\s*\."),
    re.compile(r"urllib\s*\."),
]


class InputValidationError(ValueError):
    """Raised when user input fails validation."""

    def __init__(self, field: str, reason: str):
        self.field = field
        self.reason = reason
        super().__init__(f"Invalid {field}: {reason}")


def sanitize_question(question: str) -> str:
    """Sanitize a user's natural language question before LLM injection.

    Steps:
    1. Normalize unicode (NFKC)
    2. Strip leading/trailing whitespace
    3. Enforce length limit
    4. Check for prompt injection patterns
    5. Remove non-printable characters

    Args:
        question: Raw question string from the user.

    Returns:
        Sanitized question string safe for LLM injection.

    Raises:
        InputValidationError: If the question fails validation.
    """
    if not question or not question.strip():
        raise InputValidationError("question", "Question cannot be empty.")

    # 1. Unicode normalization
    question = unicodedata.normalize("NFKC", question)

    # 2. Strip whitespace
    question = question.strip()

    # 3. Length limit
    if len(question) > MAX_QUESTION_LENGTH:
        raise InputValidationError(
            "question",
            f"Question exceeds maximum length of {MAX_QUESTION_LENGTH} characters.",
        )

    # 4. Prompt injection detection
    for pattern in _PROMPT_INJECTION_PATTERNS:
        if pattern.search(question):
            logger.warning("Potential prompt injection detected in question: %.80s", question)
            raise InputValidationError(
                "question",
                "Question contains disallowed content. Please ask a data-related question.",
            )

    # 5. Remove non-printable characters (keep newlines/tabs)
    question = re.sub(r"[^\x09\x0A\x0D\x20-\x7E\u00A0-\uFFFF]", "", question)

    return question


def validate_generated_code(code: str) -> None:
    """Validate LLM-generated pandas code for dangerous patterns.

    This is a defense-in-depth check. The primary sandbox is the exec()
    environment with a restricted __builtins__. This check provides an
    early warning before we even attempt execution.

    Args:
        code: Python code string generated by the LLM.

    Raises:
        InputValidationError: If dangerous patterns are found.
    """
    for pattern in _DANGEROUS_CODE_PATTERNS:
        match = pattern.search(code)
        if match:
            logger.error(
                "Dangerous code pattern detected in LLM output: %s (match: %r)",
                pattern.pattern,
                match.group(0),
            )
            raise InputValidationError(
                "generated_code",
                f"Generated code contains disallowed pattern: {match.group(0)!r}. "
                "Please rephrase your question.",
            )


def sanitize_filename(filename: str) -> str:
    """Sanitize an uploaded filename for safe storage and display.

    Args:
        filename: Original filename from upload.

    Returns:
        Sanitized filename with safe characters only.

    Raises:
        InputValidationError: If filename is empty or too long.
    """
    if not filename:
        raise InputValidationError("filename", "Filename cannot be empty.")

    # Normalize and strip
    filename = unicodedata.normalize("NFKC", filename).strip()

    # Length check
    if len(filename) > MAX_FILENAME_LENGTH:
        raise InputValidationError(
            "filename",
            f"Filename exceeds maximum length of {MAX_FILENAME_LENGTH} characters.",
        )

    # Replace path traversal characters
    filename = re.sub(r"[/\\\.]{2,}", "", filename)
    filename = filename.replace("/", "_").replace("\\", "_")

    # Allow only safe characters
    filename = re.sub(r"[^\w\s\-\.\(\)]", "_", filename)

    return filename
